[storage]
driver = "overlay"
graphroot = "/home/podman/.local/share/containers/storage"
runroot = "/run/user/1000/containers"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,fsync=0"
