[containers]
cgroupns = "host"
cgroups = "enabled"
default_sysctls = []
ipcns = "host"
netns = "host"
userns = "host"
utsns = "host"
[engine]
cgroup_manager = "cgroupfs"
events_logger = "file"
runtime = "runc"
