[containers]
cgroupns = "host"
cgroups = "enabled"
default_sysctls = []
ipcns = "host"
netns = "host"
userns = "host"
utsns = "host"
volumes = [
  "/proc:/proc",
]

[engine]
cgroup_manager = "cgroupfs"
events_logger = "file"
runtime = "runc"

[engine.runtimes_flags]
runc = ["root=/run/user/1000/runc"]
