[containers]
cgroupns = "host"
cgroups = "disabled"
default_sysctls = []
ipcns = "host"
netns = "host"
userns = "host"
utsns = "host"
volumes = [
    "/proc:/proc",
]

[engine]
cgroup_manager = "cgroupfs"
events_logger = "file"
